added Feature keep on display
blastrock/kakugo pull request #55
Opened 2020-09-26 21:37 UTC by jonycoo

I've already Implemented it,
if you want Include it in the next release
Resolve Feature of Issue #54
please reply if I need to change anything before merge.
Thanks

2020-10-06 17:58 UTC, blastrock requested changes
Thanks a lot for the contribution!

I have left you a few comments. Also, if you want to, you can add your name in the AUTHORS file with description like "keep screen on option".

2020-10-06 17:58 UTC, blastrock commented on app/src/main/java/org/kaqui/testactivities/TestActivity.kt
> +            window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
Please format the files. It's Alt+Shift+L on Android Studio.

2020-10-06 17:58 UTC, blastrock commented on app/src/main/res/values/strings.xml
> +    <string name="keep_on_sum">Screen keeps lit in Study</string>
Can you rename the string to "keep_screen_on_summary"? Also, I'd write "Keep screen lit during tests".

2020-10-06 17:58 UTC, blastrock commented on app/src/main/res/values/strings.xml
> +    <string name="screen_keep_on">Keep on</string>
Can you rename this string to keep_screen_on? And write "Keep screen on" as the option name.

2020-10-10 13:14 UTC, jonycoo reviewed
changes committed in d749b5fb065c0fe78285e37b5cc9e3e4fd257ce7

2020-10-11 17:41 UTC, musotec commented
Apologies if I state anything wrong about the architecture, I only now have taken a cursory look at the structure of this app.

I think it would also be preferable to have keep awake on only when the user is in a TestFragment. This way a user either viewing stats or leaving any of the quiz selection windows open does not keep the screen on and draining battery.

Consider adding the removal of the keep awake window flag on the fragment transition (https://github.com/blastrock/kakugo/blob/47e28993165268f8da4461d873eee71f1369b0a1/app/src/main/java/org/kaqui/testactivities/TestActivity.kt#L307)

Window flags can be cleared using:
`window.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)`

This is recommended in this official documentation: https://developer.android.com/training/scheduling/wakelock#screen

2020-10-13 16:50 UTC, blastrock commented
> I think it would also be preferable to have keep awake on only when the user is in a TestFragment. This way a user either viewing stats or leaving any of the quiz selection windows open does not keep the screen on and draining battery.

This PR puts the flag on the TestActivity, which always contain a TestFragment. I don't think putting it there would change anything.

From what I understand from the documentation, it is fine to put it in the activity, as @jonycoo did. Android will disable the feature when you switch app, or when you go back I guess... It will be easy to test.

If it doesn't work that way, we can set the flag and clear it in onStart/onStop.

2020-10-21 11:09 UTC, blastrock approved these changes
It does work, the screen is kept on only when the test activity is open.

Thanks for your contribution!

2020-10-21 11:09 UTC, merged